- README.md
I have noticed some grammatical mistakes in **README** inside section "**Styles template**"
"**For now you have access**"  should be "**For now, you have access**"
Screenshot-
> Update README.md - enhancement.

- README.md
Changed the instructions to reference the Frontend tab not the Integrations tab in HACS, as this is a Frontend Integration
> Correct error in HACS Installation instructions

- src/cards/pop-up.ts
Fixes #370
`getVariables` takes a little bit of time, likely due to DOM manipulations.
Move initial hiding popup logic sooner than reading config
<details>
<summary>Broken Preview (Epilepsy warning)</summary>
</details>
<details>
<summary>Fixed Preview (Epilepsy warning)</summary>
</details>
> Hide popup related vertical cards sooner

- src/cards/button.ts
- src/cards/cover.ts
- src/cards/horizontal-buttons-stack.ts
- src/cards/pop-up.ts
- src/tools/tap-actions.ts
Here is another PR to fix a bug I encounter:
I am on mobile an I try to scroll my page. If my scroll starts on a bubble-card, it execute the action even if my drag ends on another element (not really sure which one -probably hold-). This is caused by the mouse events behavior which is a bit different than the mouse ones.
To solve this, I used the pointer events, that should be compatible anywhere (I don't have an iPhone, so I can't be sure it's working fine on iPhone, but desktop and Android are OK).
I also change a bit how `ActionHandler` works: this allows to reduce the amount of timeout executed in the page.
Finally, some arguments were not used so I removed them.
> fix: mobile drag open execute the actions

- src/bubble-card.ts
- src/cards/horizontal-buttons-stack.ts
- src/tools/init.ts
Using `editMode` property provided by HomeAssistant cards, is way more resource efficient than querying HTML elements every 100ms
Also the `setInterval` was called on every `hass` update, and not cleaned up, it caused build up of running 100ms intervals forever for each entity update.
> Use built in HomeAssistant's built in `editMode`

- src/cards/horizontal-buttons-stack/changes.ts
- When two HBS button have the same update_time, they are looping the reorder
> fix: HBS buttons reorder when identical updated_time

- src/cards/horizontal-buttons-stack/index.ts
- I fix a scenario when the HBS card jumps on Safari if there it's scrollable
> fix: avoid hbs jump on mobile safari

- src/tools/utils.ts
When we force no scroll, there is currently no possibility to update the actual state.
I'm fixing this in this PR, closing #533
> fix: no-scrolling effect should still update state

- src/cards/button/styles.ts
- src/tools/tap-actions.ts
Trying to solve #533, I end up seeing that the feedback element became clickable and prevent the buttons to be "double_clicked"
- I add a `pointer-event: none` css on the feedback element
- I clean a bit `doubleTapTimeout` to use the constant from the top of the file
- I reset the timeout variable when cleared
Check with #533 if it solves the issue.
> fix: Prevent the feedback element to be clicked

- src/tools/global-changes.ts
- src/tools/utils.ts
Currently, we can only get a specific attribute in the sub_buttons. If it works in the majority of the cases, we can't get data from forecast for example, which is accessed with something like: `forecast[0].templow`
- I'm making an eval in the `getAttribute` method to have the possibility to get a deeper value
- I change some comparisons to compare an empty string so it allows 0 (it could be a valid value: eg. 0mm rain forecast)
- I complement the usage of `formatEntityAttributeValue`: it's not powerful enough to get deep values.
> feat: allow deep attribute in sub_buttons

- src/tools/global-changes.ts
Some user report that the attributes are sometime plained displayed.
It's the case when an attribute is no longer available (for example with media players)
I change the attribute behavior to use the `getAttribute` method to ensure an empty string if the attribute does not exist.
> fix: attributes unavailable should be hidden

- src/tools/global-changes.ts
If an attribute is 0 (for example 0mm rain forecasted, 0 degree, 0 km/h wind speed), it's not displayed in the sub-buttons
I change the conditions to check that the value is an empty string or not: empty means it is actually empty while 0 means it's actually not empty.
> fix: 0 is a valid attributes, state or last change

- src/tools/utils.ts
Context:
Binary Sensor were not recognized by Bubble Card.
What did I do:
If no icon is found, I get the one from the entity device_class
> fix: recover icon from binary_sensors

- src/cards/cover/changes.ts
pull-request for issue #773 
I hope, I've done the right, because it's my first pull-request.
> fix icon variable in cover-card

- src/tools/utils.ts
Context:
Google Wifi has a special "Online" state when available
What did I do:
I add an "online" value to the active status
I force lowercase the state to be sure the detection is consistent
> fix: support Google Wifi Online value as active

- src/tools/tap-actions.ts
Context:
Hold action is fired too fast and prevent the scroll
What did I do:
- I change the delay to 500ms to be consistent with Home Assistant hold delay
- I reset the timer on scroll
> fix: do not fire hold if a scroll is made

- src/tools/global-changes.ts
> Fixes missing '•' when state is not shown but Attribute and LastChanged are

- src/cards/media-player/changes.ts
Solves
---
#994 
Cause
---
The opacity was set on the sub-button-container without checking if this existed. 
Solution
---
Check if sub-button exist before setting the opacity.
> Add check if sub-button-container exist and then set opacity

- src/tools/utils.ts
Hi @Clooos 👋 
I started receiving some errors when I upgraded from 2.3.0 to 2.3.1 (and higher). Not an expert by any means but I believe the below error can be easily fixed by adding a safety net when fetching attributes (in case an entity is not provided).
I tested this locally and it seems to work fine.
> fix: attribute fallbacks within getImage

- src/cards/pop-up/create.ts
```yaml
type: grid
cards:
- type: vertical-stack
cards:
- type: custom:bubble-card
card_type: button
button_type: name
show_icon: true
icon: mdi:link
name: Go To Sun Pop-up
tap_action:
navigation_path: "#Bubble-Test-Sun"
button_action:
tap_action:
action: navigate
navigation_path: "#Bubble-Test-Sun"
- type: vertical-stack
cards:
- type: custom:bubble-card
card_type: pop-up
hash: "#Bubble-Test-Sun"
- type: custom:bubble-card
card_type: button
button_type: state
entity: sun.sun
title: title
```
<details>
<summary>Before</summary>
See #1003
</details>
<details>
<summary>After</summary>
</details>
- This PR fixes or closes issue: fixes #1003 
- This PR is related to issue or discussion: / 
- Link to documentation pull request: / 
No
If user exposed functionality or configuration variables are …
> Add back the population of the context.cardtitle for the pop-ups to solve #1003

- src/cards/horizontal-buttons-stack/changes.ts
This is an attempt to fix #780, where the order of the buttons in the horizontal buttons stack would constantly flip around, if any button has no PIR sensor attached.
I couldn't test this change yet, but looking at the code, there seems to be an obvious typo, that explains the buggy behavior well.
Note the missing `4_pir_sensor` for Settings. All other buttons have one defined.
```yaml
type: custom:bubble-card
card_type: horizontal-buttons-stack
auto_order: true
1_link: "#living-room"
1_name: Living Room
1_icon: mdi:sofa-outline
1_entity: light.couch
2_link: "#dining"
2_name: Dining
2_icon: hue:room-dining
2_entity: light.dining_area
3_link: "#bedroom"
3_name: Bedroom
3_icon: mdi:bed-king-outline
3_entity: light.bedroom
4_link: "#settings"
4_name: Settings
4_icon: mdi:wrench-outline …
```
> fix(h-buttons-stack): #780 unstable order, if PIR missing

- src/tools/style-utils.js
Bug: card customization is ignored if a module applies the same css
Description:
Prioritize the customization performed at the card's `styles` attribute over the module. Since the card's `styles` attribute is card specific it makes sense that that should override anything in a `module` seeing how modules are generic. This will allow user's to customize modules or set default behavior but override that behavior under certain conditions. For example, my use case where I discovered this bug was that I had a default animation for all my icons but fans spun. The way the code is written today, the fan would never spin and instead only ever do that default animation.
Remaining consistent, this also makes the JS from the card's `style` run second. This allows the user's js to customize things set …
> fix(modules): prioritize the styles written in the card over modules

- README.md
- src/editor/bubble-card-editor.js
- src/tools/global-changes.js
I would not consider it a breaking change as it only breaks an undocumented and incorrect behavior. However, for clarity's sake...
In the `yaml` if you were using `show_last_updated` instead of `show_last_changed`, it will now actually show the last updated value instead of the current behavior of showing the last changed value. This behavior in my opinion is a bug but wanted to state it here in case it [broke someone's workflow](https://xkcd.com/1172/). 
Fixes a bug. I can make a bug report if you want. I had not as I thought I'd just make a PR instead. 
The bug is that `show_last_updated` in the yaml is treated as an alias for `show_last_changed`. This means if someone were to use it, the resulting time stamp would be incorrect since last changed and last updated, although can be the …
> feat(show_last_updated): initial implementation

- src/tools/tap-actions.js
In order to differentiate between a single tap and a double tap, there needs to be a delay after the first tap. Otherwise, the action of the first tap will be executed prematurely.
Unfortunately, that adds a delay to any single tap action. In this case, the delay was set to 200 milliseconds, which is way more than the latency of many devices.
The solution is simple – in most cases, people don't even use double tap, so we can avoid the delay entirely. That's what this commit does.
Tested locally, works great, the difference is very noticeable.
Related discussion: https://github.com/Clooos/Bubble-Card/discussions/288
> Fix sluggish buttons when double-tap is disabled

- README.md
- src/bubble-card.js
- src/cards/button/create.js
- src/cards/button/editor.js
- src/cards/climate/editor.js
- src/cards/cover/editor.js
- src/cards/media-player/editor.js
- src/editor/bubble-card-editor.js
- src/tools/tap-actions.js
The downside of having not `none` double tap action is that it adds a 200ms delay to any tap action, which is noticeable and quite annoying. Therefore, it seems that `none` is really the best default.
This PR can be merged after this one: https://github.com/Clooos/Bubble-Card/pull/1392
> Switch the default double-tap action to `none`

- src/tools/utils.js
Zero values meaning “off” is the current behavior of the latest release, and it is quite useful. For most units, 0 is indeed the absence of something.
In #1213, it was reported that temperatures are an exception to that. Indeed! However, the fix made it treat all numeric values as “on”, and that's not cool!
This commit reverts back the previous behavior, and adds a special case for temperatures. Now, all units should behave just fine!
Some examples with power (W):
> Treat 0 values as “off”

- src/components/slider/create.js
- src/tools/utils.js
Ideal throttle function should:
1. React immediately to the first event
2. Process no more than 1 event within the time specified by the delay
3. Always process the last event
* Failing to do ① will result in no action for singular events – e.g.
you try to change the light color by just clicking on the slider, but
nothing happens if you keep holding without moving
* Failing to do ② will result in actions being fired too fast – e.g.
you stopped moving the mouse and also released the mouse button, now
the device will receive two different values at almost the same time
* Failing to do ③ will result in the value being stuck at some point
during dragging, and not at the final point – e.g. you drag the mouse
past the 100% and stop, the value won't end up at 100%
The goal of this commit was to …
> Make throttle function reliable

- src/components/slider/create.js
Without this, releasing the mouse click over other elements will trigger their click events, which can be disastrous. For example, when sliding a value to 0, it's typical to end up over the navigation drawer, meaning that the moment the user releases the click, they'll be sent to a completely different page.
This issue was generally not noticeable on mobile devices, but on desktop it was quite annoying.
> Fix `click` propagation
